### ISSUE TITLE
Type declarations

### ISSUE THREAD

**Issue by moomoolive** [darionco/WebCPU#14]
Hey man,

Thanks for this awesome library! 

I noticed there weren't any Typescript definitions for it, so I created it myself, add it to the source library if you're interested.

Here is the declaration:
```
declare module "webcpu" {
    interface DetectionOptions {
        hardcore?: boolean
        estimateInNode?: boolean
    }

    interface WebCPUResults {
        reportedCores: number | null
        estimatedIdleCores: number
        estimatedPhysicalCores: number
    }

    interface WebCPULib {
        detectCPU: (options?: DetectionOptions) => Promise<WebCPUResults>
    }

    export const WebCPU: WebCPULib 
}
```

cheers,

**Comment by darionco** [comment]
Awesome, thank you for this!

Would you be interested in submitting a PR so you appear as a contributor? if not, I'll just add a definition file with your code.

Cheers!

**Comment by moomoolive** [comment]
Yeah sure, I'll do that!
